<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>swagSMB</RootNamespace>
    <AssemblyName>swagSMB</AssemblyName>
    <Platforms>AnyCPU;x64;x86;ARM64</Platforms>
    <ApplicationIcon>../../.resources/icon/swag.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="../version" Link="version">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../../.resources/icon/swag.ico" Link="swag.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ookii.Dialogs.WinForms" Version="4.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
    <PackageReference Include="SMBLibrary" Version="1.5.7" />
    <PackageReference Include="SMBLibrary.Win32" Version="1.4.3" />
  </ItemGroup>
</Project>
